apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgCCrSEnuJj+0sICabbj62VwFoyUrTs1ZVeUF8WACOLtDOp5W0JIj/EleKfnzsNZcE+rIYxCk03WnOQnJgFjgAlkG6gOwYOJkfccPqC+KXy+wNF2yQ4KdaD8ImGW1wHldl8bXNB8QW6kQOufxLxqsEJcnedRubrcdZEjhLfoi/KdZgNmKCMLvLLZbb1P6u81/JNH8Z7F2rNnXhcQIah6lhVzfnhVk2LzzxGivpFg1/0GGeAm7QoWs0LA+nIJcaI+SBtkdJPgtOQD1q0jLiGQ3C5LXaewS6Y35ygBBrzSaHq53lqhIe0arw6bmQ/8JX8xkVLNuy7pOx6edOaRhwsi/7MsQ2TMq5vnflMBSoZM/O4cL8sp9nRyUVc2AVtnPr3+5ayU7EZLuoqJJvSC2rQvttDUO7PBhEdTXFWbc3XrsdEGFhF0IxY8/4jJOqs29Q0lNd/6G0p/xnXyh99gTb/T1nn73uR2ydSm6+iOMpEdkt+iFU5Zm565rjSkfsJ0gM2zRpvOeA6HybapRseNdVGTfsy809WCDXeODUB8ReswFvTIfoHzf0O1flm6e4bzDtQZY2JvIsHAR+jHQMlicZQd7J+hk+qPuLF/MjMOKJTYwghv3XcEvEOM6MyLFTdEGag5N2pfvoOa3MiO8ItBAANzmJ21jC54kGd6WO5p3Lst6PWKy669DVrJCtV2RiY++uhG31UaCLZdYcNFvxLZDdrCGb/kWgjIFAcM4uHF
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

